// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybrklodcpkuapyoijpab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlicmtsb2RjcGt1YXB5b2lqcGFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDQ1OTQsImV4cCI6MjA3MTk4MDU5NH0.LhCEZ8Q7U5YWHtXiZgn9U_mbhLZPHTnxBNzCiJmT1Xk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});